config/routes.rb
Nzitat::Application.routes.draw do

  resources :users

  resources :attendees

  resources :events do 
    resources :subscriptions
  end

  root :to => 'events#new'

end

app/models/appointments.rb
class Appointments < ActiveRecord::Base
  # attr_accessible :title, :body
  


end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :avatar, :status, :title
end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :description, :event_end, :event_start, :status, :title, :date, :time

  attr_accessor :date, :time

  before_validation :set_datetime

 #belongs_to :user

  has_many :subscriptions

  validates :event_start, :presence => true
  validates :title, :presence => true, :uniqueness => true
  
  def populate_time
    self.date = event_start.strftime('%Y-%m-%d')
    self.time = event_start.strftime('%I:%M%p')
  end

  scope :coming_events, where('event_start > ?', Time.now)
  scope :past_events, where('event_start < ?', Time.now)

  def has_happened?
    event_start < Time.now
  end

  private
  def set_datetime
    if date.present? && time.present?

      self.event_start = Time.parse([date,time]*' ').utc

    end

  end

end

app/models/event_reminder.rb
class EventReminder < ActiveRecord::Base
  attr_accessible :notify_at
  belongs_to :event
  validates :notify_at, presence: true
  scope :pending, where(delivered_at: nil).where("notify_at <= ?", Time.now.utc)

  def self.deliver
    Mailer.event_reminders(pending)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  
  validates :email, :format => { :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ }
  
  attr_accessible :user, :event, :email

  belongs_to :user
  belongs_to :event

  attr_accessor :email

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :format => { :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ }

  has_many :subscriptions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  
  before_filter :populate_time, only: :edit

  def index 
    @events = Event.order('event_start ASC')
    @past_events = Event.past_events
    @coming_events = Event.coming_events
  end

  def show
    @subscription = Subscription.new
    show!
  end

  private
  def populate_time
    resource.populate_time
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < InheritedResources::Base

  def create
    @event = Event.find(params[:event_id])
    @subscription = @event.subscriptions.new(params[:subscription])
    @user = User.find_or_create_by_email(@subscription.email)
    @subscription.user = @user
    if @subscription.save
      create! { event_path(@event) }
    else
      
      redirect_to @event
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  def show
    @user = User.find(params[:id])
    respond_to :html
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def timeago(time, options = {})
    content_tag(:time, time.to_s, options.merge(:datetime => time.getutc.iso8601)) if time
  end

  def event_time_select(field)
  times = %w(AM PM).collect do |ampm|
    (0..11).to_a.collect do |hour|
      (0..45).step(15).to_a.collect do |minutes|
        '%02d:%02d%s' % [hour == 0 ? 12 : hour, minutes, ampm]
      end
    end
  end.flatten
  collection_select(:event, :time, times, :to_s, :to_s, :prompt => true)
end

  def homepage?

    controller_name == 'events' and %w(new create).include?(action_name)

  end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<h1>Listing attendees</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Avatar</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendees.each do |attendee| %>
  <tr>
    <td><%= attendee.title %></td>
    <td><%= attendee.avatar %></td>
    <td><%= attendee.status %></td>
    <td><%= link_to 'Show', attendee %></td>
    <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
    <td><%= link_to 'Destroy', attendee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @attendee.title %>
</p>

<p>
  <b>Avatar:</b>
  <%= @attendee.avatar %>
</p>

<p>
  <b>Status:</b>
  <%= @attendee.status %>
</p>


<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>

app/views/events/_form.html.erb
<div class="row" id="create_events">
  
  <%= simple_form_for @event, :html => {:class => ''} do |f| %>
    <div class="span12" style="text-align: center">
       <%= image_tag('logo.png') %>
      <%= f.input :title, :label => false, :placeholder => 'event name'  %>

      <%= f.input :date, :as => :string, :input_html => { :class => 'datepicker'}, :label => false, :placeholder => 'what day?'  %>
      <% # f.input :time, :label => false, :placeholder => "what time?" %>
      <%= event_time_select(:time) %>
      <br/>
      <%= f.button :submit, :class => "btn-info btn-large"  %>
    </div>
  <% end %>
  <br/>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row" style="text-align:center">

  <div class="page-header">
    <h1>All Events</h1>
  </div>
  <div class="span3 offset3">
  <h3>Past Events</h3>
    <% @past_events.each do |event| %>
    <div class="event">
      <h3><%= link_to event.title, event %></h3>
      <p><%= timeago(event.event_start) %><br/>
        <%= event.subscriptions.count %> attendees</p>
      
    </div>
  <% end %>
</div>
<div class="span3">
  <h3>Coming Events</h3>
   <% @coming_events.each do |event| %>
    <div class="event">
      <h3><%= link_to event.title, event %></h3>
      <p><%= timeago(event.event_start) %><br/>
        <%= event.subscriptions.count %> attending</p>
    </div>
  <% end %>

</div>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div id="event_new" class="span12">

    <h1>
      <%= timeago(@event.event_start) %>
    </h1>

    <h3><%= @event.has_happened? ? ' since ' : ' until ' %> <%= @event.title %></h3>

  </div>
</div>

<div class="row">
  <div class="offset3 span4">

    <h3><%= @event.has_happened? ? 'Who Came Along' : 'Who\'s Coming?' %></h3>
    <% if @event.subscriptions.empty? %>
      <p>No one.</p>
    <% else %>
      <% @event.subscriptions.map(&:user).uniq.each do |user| %>
        <%= link_to user.email, user %><br/>
      <% end %>

    <% end %>
  </div>
  <div class="span4">
    <h3>Follow this event</h3>
    <%= simple_form_for([@event, @subscription]) do |f| %>

      <%= f.input :email, :label => false %>

      <%= f.button :submit, "Alert me", :class => 'btn btn-info' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nzitat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer style="text-align: center"> 
      <p style="color: #999">&copy; figjam productions <%= link_to 'See all events', events_path %>

      <% unless homepage? %>
        <%= link_to('Add New', new_event_path, :class => 'btn btn-info')  %>
      <% end  %>


    </p>
    </footer>

  </div> <!-- /container -->

  <!-- Javascripts
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/ﬂuid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nzitat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Nzitat</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= semantic_form_for [@event, @subscription] do |f| %>
  <%= f.input :email %>
<% end %>

app/views/users/show.html.erb
<div class="row" style="text-align: center">

  <h1> <%= @user.email  %></h1>

  <% if @user.subscriptions.count >= 1 %>
    <div class=" offset4 span4">is going to:<br/>
      <% @user.subscriptions.each do |e| %>
        <%= e.event.title %> <%= timeago(e.event.event_start) %><br/>
      <% end %>

    </div>
    <% end %>
  </div>